### ISSUE TITLE
Could not pass event InventoryClickEvent to SurveyPlus v1.7.2

### ISSUE THREAD

**Issue by Andre601** [MartenM/SurveyPlus#3]
```
>.... [23:30:22 ERROR]: Could not pass event InventoryClickEvent to SurveyPlus v1.7.2
java.lang.IllegalStateException: AsyncSurveyStartEvent may only be triggered asynchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:531) ~[patched_1.14.4.jar:git-Paper-186]
at nl.martenm.surveyplus.objects.surveySessions.SurveyHandler.startPreviewSurvey(SurveyHandler.java:54) ~[?:?]
at nl.martenm.surveyplus.inventories.SurveyListMenu$1.lambda$run$0(SurveyListMenu.java:119) ~[?:?]
at nl.martenm.surveyplus.listeners.InventoryClickListener.handleEvent(InventoryClickListener.java:38) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor37.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-186]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-186]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-186]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-186]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by MartenM** [comment]
Please update to the latest version. This should now be resolved.
