### ISSUE TITLE
Book Survey not working on 1.16.4

### ISSUE THREAD

**Issue by Mikronami** [MartenM/SurveyPlus#5]
After trying to open the book survey I got an exception.
My server is running on 1.16.4 with PaperMC.

[14:51:08] [Server thread/WARN]: [SurveyPlus] Task #73148 for SurveyPlus v1.7.6 generated an exception
xyz.upperlevel.spigot.book.NmsBookHelper$UnsupportedVersionException: Error while executing reflections, submit to developers the following log (version: v1_16_R3)
	at xyz.upperlevel.spigot.book.NmsBookHelper.setPages(NmsBookHelper.java:145) ~[?:?]
	at xyz.upperlevel.spigot.book.BookUtil$BookBuilder.pages(BookUtil.java:136) ~[?:?]
	at nl.martenm.surveyplus.survey.BookSurvey.welcomePlayer(BookSurvey.java:51) ~[?:?]
	at nl.martenm.surveyplus.objects.surveySessions.SurveySession$1.run(SurveySession.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at xyz.upperlevel.spigot.book.NmsBookHelper.setPages(NmsBookHelper.java:139) ~[?:?]
	... 11 more

**Comment by MartenM** [comment]
Should be fixed in the latest release.
